version: '3'

services:
  database:
    container_name: db-course-platform
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=course
    ports:
      - 3306:3306
    volumes:
      - ./mysql-vol:/var/lib/mysql